### ISSUE TITLE
Using your code

### ISSUE THREAD

**Issue by timstoop** [egeland/nagios-rbl-check#1]
Hey man,

Thanks for the code, works great! We're adding it to our package with nagios plugins and I modified it a bit so it also access IP addresses. And works as expected on Python 2.6, so changed that check as well. Of course you're free to incorporate our changes, but I'm afraid I had to add it by copy/pasting, so there's not a clean commit you can add.

You can find it here: https://github.com/kumina/nagios-plugins-kumina

Have fun!

**Comment by egeland** [comment]
Hi @timstoop - I've given you commit access to this repo, so if there are any changes you needed to merge it, you can do so now.
