### ISSUE TITLE
Server x thinks ip is on blacklist, Localhost and hostkarma.junkemail.com don't agree with Server x

### ISSUE THREAD

**Issue by agroendijk** [egeland/nagios-rbl-check#15]
Hi,
When I do a blacklist check on 109.71.52.93 from our server, this gives a warning. When I check it from my localhost, it doesn't give a warning. The check on Junkemail's site returns: 
> 109.71.52.93 is Yellow listed - This is a good listing. It keeps you from being blacklisted. Yellow means that your IP contains no information as to whether or not it is spam. Yahoo, Google, and Hotmail are Yellow Listed.

Junkemail about 'Yellow listed'
> A yellow listed server is a mail server that sends out some spam. These would be services like Yahoo, Hotmail, and ISPs who try to get rid of outgoing spam but can't catch it all. If you are yellow listed we will never black list you and we don't check other lists to see if you are blacklisted.

![image](https://cloud.githubusercontent.com/assets/4597686/26389396/0ef8a458-405a-11e7-97c7-60735e07f45e.png)

Any thoughts on this?

**Comment by egeland** [comment]
Seems like the simplest solution is to remove Junkemail from the list..?

Anyone else have any ideas?

**Comment by non7top** [comment]
May be there is/was some dns caching in effect?

**Comment by egeland** [comment]
Good point - is it still happening, @agroendijk ?

**Comment by agroendijk** [comment]
Maybe it was caching. I've put 'Junkemail' back to the list again, and I didnt get any messages. But.. how is this possible? Can we rely on this check or is it caching the results? Maybe something to find out?

**Comment by non7top** [comment]
DNS is being cached, which is not related to this script.

**Comment by egeland** [comment]
Yes, the script itself does not do any caching.

I'll close this issue since it seems to have resolved itself. :smile:
