### ISSUE TITLE
Add a debug or verbose option

### ISSUE THREAD

**Issue by altmas5** [egeland/nagios-rbl-check#16]
Hello guys,

I would be very helpful to have a debug or verbose option to check which RBL's are timing out or not returning an answer at all.
This is needed when the plugin execution time exceeds the timeout for the command.

I will try to submit a pull request with this changes soon but I want to know if you think it's accepted or maybe there is a more simple way to get this info.

Regards

Regards

**Comment by egeland** [comment]
Sounds like it would be a useful feature! 👍

**Comment by altmas5** [comment]
Ok @egeland.
Do you think the option it should be used as `--debug` or `--verbose`?

**Comment by egeland** [comment]
I'm leaning towards --debug
