### ISSUE TITLE
Travis Failing on Python 2.6

### ISSUE THREAD

**Issue by smashedr** [egeland/nagios-rbl-check#20]
Looks like this commit 419b014a6093da0e76ff2d1df48103eda6d6ba05 is causing the script to break on python 2.6 according to Travis. 

The effected line is:

https://github.com/egeland/nagios-rbl-check/blob/master/check_rbl.py#L33

PS: I also already updated this for Python3 and managed to not break python 2.6:

https://github.com/smashedr/nagios-rbl-check3

Edit: actually, it looks like this does break Travis on python 2.6, seems I commented it out. If anyone can think of a fix that would be great. Otherwise, I can just comment out 2.6 from travis,.yml.

**Comment by hmoffatt** [comment]
Thanks, I fixed it for all versions now. If you have any other improvements in your fork please send pull requests.
