### ISSUE TITLE
Add senderbase check (talosintelligence.com)

### ISSUE THREAD

**Issue by josvo** [egeland/nagios-rbl-check#22]
Hi

Would it be possible to add a senderbase check?
See here: https://www.talosintelligence.com/reputation_center

It is possible to do an online lookup but I'm not sure if the data is available for an automated check. 
Thanks

**Comment by egeland** [comment]
Hi,

That is a very different kind of lookup from the DNS based ones we do in this plugin.
If I was going to create a check for this, I'd make a new plugin. But first, see if the lookup form can be used via `curl`, or if it's relying on a bunch of JavaScript.
Looks like a fun little project! 😃

If you, or anyone else reading this, do create it, please put a link to your efforts in this ticket. 👍

Good luck!

**Comment by egeland** [comment]
Probably safe to close this issue now...
