### ISSUE TITLE
Add two new Blacklists

### ISSUE THREAD

**Issue by brandau-it-solutions** [egeland/nagios-rbl-check#23]
Hi,
Would it be possible to add the two blacklists to rbl-check?

http://www.anti-abuse.org
http://rbl-check.org

Thanks

**Comment by altmas5** [comment]
Hello @brandau-it-solutions,

It looks like those sites you sent perform checks using a list of RBLs, so are not RBLs themselves.
Because of that I would say this this issue is not valid.

If you find an additional RBL which can be added please share it with us.

Regards.
