### ISSUE TITLE
setDaemon is deprecated since python 3.10

### ISSUE THREAD

**Issue by tobox** [egeland/nagios-rbl-check#30]
Using 

    threading.Thread.__init__(self, daemon=True)

instead of 

    t.setDaemon(True)

seems to be the obvious fix.

**Comment by smashedr** [comment]
This was fixed in: https://github.com/egeland/nagios-rbl-check/pull/27

Make sure you are using the latest version and let us know if you still have this issue.

I can also add a PyPi release to make updating easier if anyone thinks that would be useful.

**Comment by tobox** [comment]
I just took a glance at the current version in the github web interface and misread the correct/current 
"t.daemon = True" as "t.setDaemon(True)" so I thought it was not fixed yet. Sorry for the noise :-/
